### ISSUE TITLE
Boost version

### ISSUE THREAD

**Issue by bitblaster** [sschuberth/is-procap#1]
Hi, I was trying to compile this with VS2015, but I can't match the boost version required.
I tried ( based on the date of your files) 1.36, 1.42, 1.52, 1.55, 1.73, but they all give some compilation problem, mostly in the process project.
Can you point me to the exact version you used?

**Comment by sschuberth** [comment]
I haven't compiled this project myself for about 9 years, so I'm sorry, but I don't know / remember 😞
